#!/usr/bin/env bash

export PGPASSWORD=postgres
DB_NAME="${1:-dancefinder}"
DUMP_FILES="${2:-${HOME}/Source/dancefinder/Postgres_RDS-dancefinder*.sql}"
DUMP_FILE="$(ls -1t ${DUMP_FILES} | head -1)"
echo "Restoring ${DUMP_FILE} to ${DB_NAME}"

psql -h unbound-control-plane.orb.local -U postgres -d postgres <<-EOSQL
  SELECT pg_terminate_backend(pid)
  FROM pg_stat_activity
  WHERE datname = '${DB_NAME}'
    AND leader_pid IS NULL;
  DROP DATABASE ${DB_NAME};
  CREATE DATABASE ${DB_NAME} WITH OWNER postgres ENCODING utf8;
EOSQL

psql -h unbound-control-plane.orb.local -U postgres -d ${DB_NAME} < "${DUMP_FILE}"
