#!/usr/bin/env bash

export PGPASSWORD=postgres

psql -h goodfeed-control-plane.orb.local -U postgres -d postgres <<-EOSQL
  SELECT pg_terminate_backend(pid)
  FROM pg_stat_activity
  WHERE datname = 'prod_dump3'
    AND leader_pid IS NULL;
  DROP DATABASE prod_dump3;
  CREATE DATABASE prod_dump3 WITH OWNER postgres ENCODING utf8;
EOSQL

cat "$(ls -1t ~/Source/CustomerProjects/Goodfeed/Postgres_RDS_Goodfeed_Prod-backend*.sql | head -1)" | psql -h goodfeed-control-plane.orb.local -U postgres -d prod_dump3
